defaults: &defaults
  site_name: WesACB
  email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
#  email_regex: !ruby/regexp /\A[\w+\-.]+@wesleyan.edu\z/i

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
