defaults: &defaults
  site_name: TikTak
  campus_name: TikTak
  email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

#  This line provides an alternative regex for campus/institutional use-cases.
#  email_regex: !ruby/regexp /\A[\w+\-.]+@campus-domain-goes-here.edu\z/i

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
